// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AvaloniaApplication1.Models;

public partial class Tovar
{
    public string Name { get; set; }

    public string Cost { get; set; }

    public string Opisanie { get; set; }

    public string Kolichestvo { get; set; }

}